apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mlbench.worker.fullname" . }}-sa
{{if .Values.worker.imagePullSecret}}
imagePullSecrets:
- name: {{.Values.worker.imagePullSecret}}
{{end}}