apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "mlbench.worker.fullname" . }}
  labels:
    app: {{ template "mlbench.name" . }}
    chart: {{ template "mlbench.chart" . }}
    component: "{{ .Values.worker.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "mlbench.name" . }}
      release: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: {{ template "mlbench.name" . }}
        component: "{{ .Values.worker.name }}"
        release: {{ .Release.Name }}
        role: worker
    spec:
      serviceAccountName: {{ template "mlbench.worker.fullname" . }}-sa
      containers:
        - name: {{ template "mlbench.name" . }}-{{ .Values.worker.name }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          stdin: true
          tty: true
          ports:
            - name: ssh
              containerPort: 22
              hostPort: 16166
              protocol: TCP
          # livenessProbe:
          #   tcpSocket:
          #     port: ssh
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # readinessProbe:
          #   tcpSocket:
          #     port: ssh
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: mlbench-ssh-key
            mountPath: /ssh-key/root
      volumes:
      - name: mlbench-ssh-key
        secret:
          secretName: {{ .Release.Name }}-ssh-key
          defaultMode: 256
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
