kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "mlbench.worker.fullname" . }}-rolebinding
roleRef:
  kind: Role
  name: {{ template "mlbench.worker.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "mlbench.worker.fullname" . }}-sa